### ISSUE TITLE
task scheduler not working 

### ISSUE THREAD

**Issue by AminebajjiDEV** [memstechtips/UnattendedWinstall#117] opened 2024-08-18 16:08 UTC
I was trying to set a throttlestop trigger whenever my computer starts it should start with it. the problem is task scheduler doesn't function at all i even tried setting multiple tasks with triggers

**Comment by Rekit0** [comment] 2024-10-16 04:04
I can confirm having the same issue in windows 11 23H2, i used the [Standard] 
 (https://github.com/memstechtips/UnattendedWinstall/blob/main/Standard/autounattend.xml) Unattend file.

**Comment by Beats24-7** [comment] 2024-10-22 11:16
I have a similar issue with a fresh Windows 22H2 install using the Unattended file. When opening the task scheduler I get errors that the tasks "Microsoft Comaptiblity Appraiser", "Proxy", "KeyPreGenTask", "UsbCeip", "Consolidator", "QueueReporting" are missing. However, the tasks are present within the Windows/System32/tasks folder so I cannot even import them. When removing them, renaming to .xml files and trying to import them through the scheduler again, they still cannot be imported as task scheduler says tasks with the same name already exist.
Is there any way to fix this? The tasks seem to be related to TPM, telemetry, etc... and maybe that's why they have been disabled but there shouldn't be any errors with a fresh windows install? Thanks

**Comment by memstechtips** [comment] 2024-11-06 13:18
Hey there everyone,

This should be fixed in v2.0.0 - https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0

During the creation process of v2.0.0 I realized the v1.0.0 files were deleting the scheduled tasks instead of just disabling them.

Feel free to reopen the issue if it's not fixed.

**Closed by memstechtips** 2024-11-06 13:18 UTC

**Comment by memstechtips** [comment] 2024-11-07 11:22
@AminebajjiDEV You can get the v2.0 experience by using the `UWScript.ps1` file on an existing installation. However, because the issue is that the Task Scheduler isn't working and it's because some of the tasks are deleted, I would say it's best to backup your data and do a clean install with the v2.0 file.

**Comment by AminebajjiDEV** [comment] 2024-11-07 13:13
@memstechtips It makes sense to do the a clean install. Thank you for fixing this issue!
